backend:
  name: git-gateway
  branch: master  # Change this to your main branch

logo_url: https://onememorypermile.com/images/logo-ompm.png

locale: 'de'  # Setzt die Sprache auf Deutsch

editor:
  preview: true  # Aktiviert die Vorschau im Editor

# This line should *not* be indented
media_folder: "/images" # Media files will be stored in the repo under images/uploadspublic_folder: "/assets/images/uploads"
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

 # Collection für die index.html-Seite hinzufügen
collections:
  - name: "pages"
    label: "Seiten"

    files:
      - label: "Index-Seite"
        name: "index"
        file: "index.html"  # Pfad zu deiner Index-Datei
        preview_path: index
        fields:
          - {label: "Intro Titel", name: "intro_title", widget: "string"}  # Titel
          - {label: "Intro Text", name: "intro_text", widget: "text"}  # Text
          - {label: "Intro Untertext", name: "intro_subtext", widget: "text"}  # Untertext
          - {label: "Hintergrundbild Kopffeld", name: "bg-image-roof", widget: "image"}  # Neues Bild-Upload-Feld
          - {label: "Bild erste Section", name: "bg-image-bed", widget: "image"}  # Neues Bild-Upload-Feld