backend:
  name: git-gateway
  branch: master  # Change this to your main branch

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploadspublic_folder: "/assets/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
