backend:
  name: git-gateway
  branch: master  # Change this to your main branch

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploadspublic_folder: "/assets/images/uploads"
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

 # Collection für die index.html-Seite hinzufügen
collections:
  - name: "pages"
    label: "Seiten"
    files:
      - label: "Index-Seite"
        name: "index"
        file: "index.html"  # Pfad zu deiner Index-Datei
        fields:
          - {label: "Intro Titel", name: "intro_title", widget: "string"}  # Titel
          - {label: "Intro Text", name: "intro_text", widget: "text"}  # Text
          - {label: "Intro Untertext", name: "intro_subtext", widget: "text"}  # Untertext